#pragma once

#include <memory>
#include <vector>
#include <string>
#include <list>
#include <array>
#include <map>
#include <unordered_map>
#include <future>
#include <thread>
#include <algorithm>
#include <queue>
#include <functional>
#include <Windows.h>
#include <math.h>
#include <stdint.h>
#include <filesystem>
#include <fstream>
#include <shlwapi.h>